# Generated by Django 3.1.3 on 2021-01-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_auto_20210103_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Paytm', 'Paytm')], default='Cash On Delivery', max_length=20),
        ),
    ]
