# Generated by Django 3.1.3 on 2021-01-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20210103_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Stripe', 'Stripe')], default='Cash On Delivery', max_length=20),
        ),
    ]
